# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       sofia-sip

# >> macros
# << macros

Summary:    Sofia SIP User-Agent library
Version:    1.12.11
Release:    1
Group:      Communications/Telephony and IM
License:    LGPLv2+
URL:        http://sofia-sip.sourceforge.net/
Source0:    http://dl.sourceforge.net/sofia-sip/%{name}-%{version}.tar.gz
Source100:  sofia-sip.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libssl) >= 0.9.7
BuildRequires:  pkgconfig(glib-2.0) >= 2.4
BuildRequires:  pkgconfig(check) >= 0.9.4

%description
Sofia SIP is a RFC-3261-compliant library for SIP user agents and
other network elements.  The Session Initiation Protocol (SIP) is an
application-layer control (signaling) protocol for creating,
modifying, and terminating sessions with one or more
participants. These sessions include Internet telephone calls,
multimedia distribution, and multimedia conferences.


%package glib
Summary:    Glib bindings for Sofia-SIP
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description glib
GLib interface to Sofia SIP User Agent library.

%package utils
Summary:    Sofia-SIP Command Line Utilities
Group:      Applications/Internet
Requires:   %{name} = %{version}-%{release}

%description utils
Command line utilities for the Sofia SIP UA library.

%package glib-devel
Summary:    Glib bindings for Sofia SIP development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   sofia-sip-glib = %{version}-%{release}
Requires:   sofia-sip-devel = %{version}-%{release}

%description glib-devel
Development package for Sofia SIP UA Glib library. This package
includes libraries and include files for developing glib programs
using Sofia SIP.


%package devel
Summary:    Sofia-SIP Development Package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development package for Sofia SIP UA library.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
find %{buildroot} -name \*.h.in -delete
# << install post

%check
# >> check
#TPORT_DEBUG=9 TPORT_TEST_HOST=0.0.0.0 make check
# << check

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%post glib -p /sbin/ldconfig

%postun glib -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS ChangeLog ChangeLog.ext-trees COPYING COPYRIGHTS
%doc README README.developers RELEASE TODO
%{_libdir}/libsofia-sip-ua.so.*
# << files

%files glib
%defattr(-,root,root,-)
# >> files glib
%{_libdir}/libsofia-sip-ua-glib.so.*
# << files glib

%files utils
%defattr(-,root,root,-)
# >> files utils
%{_bindir}/*
%{_mandir}/man1/*.1*
# << files utils

%files glib-devel
%defattr(-,root,root,-)
# >> files glib-devel
%{_includedir}/sofia-sip-1.12/sofia-sip/su_source.h
%{_libdir}/libsofia-sip-ua-glib.so
%{_libdir}/pkgconfig/sofia-sip-ua-glib.pc
# << files glib-devel

%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/sofia-sip-1.12
%dir %{_includedir}/sofia-sip-1.12/sofia-sip
%{_includedir}/sofia-sip-1.12/sofia-sip/*.h
%exclude %{_includedir}/sofia-sip-1.12/sofia-sip/su_source.h
%dir %{_includedir}/sofia-sip-1.12/sofia-resolv
%{_includedir}/sofia-sip-1.12/sofia-resolv/*.h
%{_libdir}/libsofia-sip-ua.so
%{_libdir}/pkgconfig/sofia-sip-ua.pc
%{_datadir}/sofia-sip
# << files devel
